runtime: nodejs18
service: github

instance_class: B2
basic_scaling:
  max_instances: 1

# instance_class: F1
# automatic_scaling:
#   max_instances: 10
#   min_idle_instances: 1
# inbound_services:
# - warmup

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  EAVE_CORE_API_URL: "https://api.eave.fyi"
  EAVE_MONITORING_ENABLED: "1"
  EAVE_TEAM_ID: "3345217c-fb27-4422-a3fc-c404b49aff8c"
