runtime: python310
service: www
instance_class: F1
automatic_scaling:
  max_instances: 10
  min_idle_instances: 1

inbound_services:
- warmup

entrypoint: gunicorn --chdir src/server eave.app:app

env_variables:
  EAVE_ANALYTICS_ENABLED: "1"
  EAVE_MONITORING_ENABLED: "1"
  EAVE_COOKIE_DOMAIN: ".eave.fyi"
  EAVE_API_BASE: "https://api.eave.fyi"

handlers:
- url: /static
  static_dir: static

- url: .*
  script: auto
