# https://console.cloud.google.com/cloud-build/triggers;region=us-central1/edit/ec977ffb-be4d-409f-bf45-d559d6f226b8?authuser=1&project=eavefyi-dev

steps:
  # - name: python:3.11.2 # gcr.io/$PROJECT_ID/eave-builder-python
  #   dir: $_EAVE_HOME
  #   entrypoint: develop/python/bin/setup
  #   env:
  #     - EAVE_HOME=$_EAVE_HOME
  #     - CI=1
  #     - VERBOSE=1

  # - name: node:20 # gcr.io/$PROJECT_ID/eave-builder-node
  #   dir: $_EAVE_HOME
  #   entrypoint: develop/javascript/bin/setup
  #   env:
  #     - EAVE_HOME=$_EAVE_HOME
  #     - CI=1
  #     - VERBOSE=1

  - name: gcr.io/$PROJECT_ID/eave-builder-node-python
    dir: $_EAVE_HOME
    entrypoint: bin/setup
    env:
      - EAVE_HOME=$_EAVE_HOME
      - CI=1
      - VERBOSE=1

  - name: gcr.io/$PROJECT_ID/eave-builder-node-python
    dir: $_EAVE_HOME
    entrypoint: bin/lint
    env:
      - EAVE_HOME=$_EAVE_HOME
      - CI=1
      - VERBOSE=1

  # TODO: start db connection

  # update db in preparation for running tests
  # - name: python:3.11.2
  #   dir: apps/core
  #   entrypoint: python
  #   args: ["-m", "alembic", "upgrade", "head"]
  #   env:
  #     - EAVE_HOME=$_EAVE_HOME
  #     - CI=1
  #     - VERBOSE=1
  #   secretEnv:
  #     - EAVE_DB_HOST
  #     - EAVE_DB_USER
  #     - EAVE_DB_PASS
  #     - EAVE_DB_NAME

  - name: gcr.io/$PROJECT_ID/eave-builder-node-python
    dir: $_EAVE_HOME
    entrypoint: bin/test
    env:
      - EAVE_HOME=$_EAVE_HOME
      - CI=1
      - VERBOSE=1

# availableSecrets:
#   secretManager:
#     - versionName: projects/$PROJECT_ID/secrets/EAVE_DB_HOST/versions/latest
#       env: "EAVE_DB_HOST"
#     - versionName: projects/$PROJECT_ID/secrets/EAVE_DB_USER/versions/latest
#       env: "EAVE_DB_USER"
#     - versionName: projects/$PROJECT_ID/secrets/EAVE_DB_PASS/versions/latest
#       env: "EAVE_DB_PASS"
#     - versionName: projects/$PROJECT_ID/secrets/EAVE_DB_NAME/versions/latest
#       env: "EAVE_DB_NAME"

substitutions:
  _EAVE_HOME: /workspace

timeout: "1800s"
