runtime: nodejs16
service: github
instance_class: F1
automatic_scaling:
  max_instances: 10
  min_idle_instances: 1

inbound_services:
- warmup

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto