runtime: python310
service: api
instance_class: F1
automatic_scaling:
  max_instances: 10
  min_idle_instances: 1

inbound_services:
- warmup

entrypoint: gunicorn --chdir src --worker-class uvicorn.workers.UvicornWorker eave.app:app

env_variables:
  EAVE_DB_NAME: "eave"
  EAVE_DB_HOST: "/cloudsql/eave-production:us-central1:eave-development"
  EAVE_MONITORING_ENABLED: "1"