runtime: python311
service: api

instance_class: B2
basic_scaling:
  max_instances: 1

# instance_class: F1
# automatic_scaling:
#   max_instances: 10
#   min_idle_instances: 1
# inbound_services:
# - warmup

entrypoint: |-
  gunicorn \
    --bind :$PORT \
    --pythonpath app,lib \
    --worker-class uvicorn.workers.UvicornWorker \
    eave:app

env_variables:
  EAVE_DB_NAME: "eave"
  EAVE_DB_HOST: "/cloudsql/eave-production:us-central1:eave-pg-core"
  EAVE_MONITORING_ENABLED: "1"
  EAVE_COOKIE_DOMAIN: ".eave.fyi"
  EAVE_API_BASE: "https://api.eave.fyi"
  EAVE_WWW_BASE: "https://www.eave.fyi"