# TODO: link to build trigger(s)

steps:
  # install dev deps so that deploy scripts work??? necessary?
  - name: python:3.11.2
    dir: apps/core
    entrypoint: bin/setup
    env:
      - EAVE_HOME=/workspace
      - CI=1
      - VERBOSE=1
      - GOOGLE_CLOUD_PROJECT=$PROJECT_ID
      - PYTHONDONTWRITEBYTECODE=1

  # installed vendored deps to be packaged w/ image
  - name: python:3.11.2
    dir: apps/core
    script: |-
      python -m pip install -t vendor -r requirements-vendor.txt
    env:
      - EAVE_HOME=/workspace

  - name: bash
    dir: apps/core
    script: |-
      cp $EAVE_HOME/.gcloudignore .
      cp $EAVE_HOME/.gitignore .
    env:
      - EAVE_HOME=/workspace

  - name: gcr.io/$PROJECT_ID/eave-builder-gcloudsdk
    dir: apps/core
    entrypoint: ./bin/deploy
    env:
      - EAVE_HOME=/workspace
      - CI=1
      - VERBOSE=1
      - GOOGLE_CLOUD_PROJECT=$PROJECT_ID

timeout: "2700s"
