runtime: python311
service: slack

instance_class: B2
basic_scaling:
  max_instances: 1

# instance_class: F1
# automatic_scaling:
#   max_instances: 10
#   min_idle_instances: 1
# inbound_services:
# - warmup

entrypoint: |-
  gunicorn \
    --bind :$PORT \
    --pythonpath vendor \
    --worker-class uvicorn.workers.UvicornWorker \
    eave_slack.app:api

env_variables:
  EAVE_CORE_API_URL: "https://api.eave.fyi"
  EAVE_MONITORING_ENABLED: "1"
  EAVE_SLACK_APP_ID: "A04HD948UHE"
